### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by befora** [befora/Kuboo#27]
https://poeditor.com/join/project/okXsdZcENf

You can contribute to the localization effort at the link above. It is public access and you can add a language if it is missing. Free service is under 1000 strings. If a language gets completed, I will import to the app and delete from Poeditor to make room.

Please keep spacing and special characters untouched. If there is string with multiple lines and blank spaces, please `COPY` the English translation and then overwrite the text to keep spacing.

Thank you.

**Comment by tomandocubatas** [comment]
Hello, 

I will try to create the localization in spanish.

**Comment by tomandocubatas** [comment]
Hi, 

I have completed the translation into Spanish. Keep in mind that some of the terms depending on the context mean one thing or another.

I have tried to translate them in the context that I think is the right one.

It would be opportune to be able to see how the application is once the imports have been made. That way I could detect if some translation is not correct.

**Comment by sethchhim** [comment]
@tomandocubatas amazing job! It looks like I need to apply some formatting and it will take a while. I will build a test apk once I'm done and post it here. I will try to rename it to like Kuboo2 or something so it won't overwrite your current app.

**Comment by sethchhim** [comment]
Ok, I did not need to format after all, it looks real good. In order for spanish to show up, your Android system language needs to be set Espanol (any region). I will also test myself for any problems. Good job!

https://drive.google.com/open?id=1-uonJY3-JydUcY83i31UEaIw91YKknoW

**Comment by sethchhim** [comment]
@tomandocubatas I also updated the English strings so it bumped your progress down to 95%

**Comment by tomandocubatas** [comment]
Goodnight,
I've been reviewing the translations and I changed some to fit more meaning.

I have seen that new properties have been added. I try to translate as soon as possible.

When you can send me a new version to continue checking.

Thanks for the effort.

**Comment by sethchhim** [comment]
@tomandocubatas Updated apk to your changes
https://drive.google.com/open?id=10x-7AIhL-ysrsu7cRpR-9wKkUrtC1kMA

**Comment by tomandocubatas** [comment]
Hello,
Proceed to test the changes this afternoon Spanish time. I'm at work now.

I give you the feedback as soon as possible.

Thank you.

**Comment by sethchhim** [comment]
@lbesnard Thank you for your work, it is much appreciated. Here is the recent snapshot apk if you would like to test it. https://drive.google.com/open?id=1RTl72XQqM8qgitwpbuRkgdm3E-K6PCAq

**Comment by lbesnard** [comment]
no worries :), thanks for a great tool ! I tested it and made a few mods.

**Comment by tomandocubatas** [comment]
Good morning,

I have made some changes in the translations.
I believe and I hope that they are all correct :)
I have also seen that there are a series of literals that continue to appear in English and that can not be translated.
For example:

Dark Theme
Location
Removed
etc.

**Comment by tomandocubatas** [comment]
ok.
No problem :+1: 
:)

**Comment by sethchhim** [comment]
@gerosyab Here is the [apk ](https://drive.google.com/open?id=1ZKdVX4CRgqfQDjt3xm6nUFLeJJA6QhZi)if you want to test it. If you need to make any adjustments, just use that website. I will most likely push korean translation in next update around the end of next week. Thank you for your contribution.

**Comment by gerosyab** [comment]
@sethchhim I am sorry but the apk you uploaded has something wrong I think. It can not be installed on my device even if I removed existing kuboo app installed from play store. Could you make and give me  new debugging apk?

**Comment by sethchhim** [comment]
@gerosyab I tested and I got this error `adb: failed to install app-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]`. I think build didnt finish or got corrupt. I rebuilt the apk and tested and this one works. My fault, I think I'm multitasking too much.

https://drive.google.com/open?id=1poHoO2nukz_V6dhl8aakWhku0c_DjTPx

**Comment by gerosyab** [comment]
@sethchhim Ok, now it works perfectly. Thank you very much! Please take it easy :)

**Comment by sethchhim** [comment]
This project has reached end of active development.
