### ISSUE TITLE
Chapter navigation in books

### ISSUE THREAD

**Issue by LazerFX** [befora/Kuboo#53]
I'd like some way of skipping to a chapter or a page number in long books - having just got a new phone while being half way through a book, I've realised I've got to page a long way to get to where I was, and I can't see anything in the UI to support jumping...

**Comment by LazerFX** [comment]
It was the reader... I wouldn't say it's bad, though I'm not an Android developer, so I can't comment on the code. I like the endless scroll functionality, and the layouts are great. Really, a press-to-jump-next would be perfect!

Either way, I know what it's like to have a project and want to make it perfect, so I'll just say it's the best ubooquity/OPDS reader for Android I've found :-)

**Comment by sethchhim** [comment]
This project has reached end of active development.
