### ISSUE TITLE
Some pages not loading with out of memory error

### ISSUE THREAD

**Issue by gotson** [befora/Kuboo#71]
Reading directly from ubooquity server, some pages won't load and the app propose to swipe down to refresh but that fails.

Closing and reopening the comic works, but that's tedious. 

I know there are options to downsize images, but honestly what's the point of having hi-res comics and hi-res screens if downsizing?

I was wondering what's the actual problem behind those errors.

**Comment by sethchhim** [comment]
`I was wondering what's the actual problem behind those errors.`

You are out of memory for the viewpager to load bitmaps. It is standard to load previous, current, and next fragments to achieve the swipe effect. Fragments out of range are recycled properly and show no signs of a memory leak [(FragmentStatePagerAdapter)](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter). Please let me know if you find any leaks, I will be happy to fix.

I have experimented with subsampling images but it still had too much overhead for production. The only option is to downsize the image to accommodate your device which I provided an option for. Most apps do this automatically which I find too restricting.

**Comment by gotson** [comment]
> Please let me know if you find any leaks, I will be happy to fix.

How can i send you anything relevant when it happens?

**Comment by sethchhim** [comment]
The app will crash and I will receive a notification in the developer console if you report it.

**Comment by gotson** [comment]
It doesn't crash, it just shows an error instead of the page.

**Comment by sethchhim** [comment]
You need to downsize the image. There is no magic way to render high resolution bitmaps without the memory cost. I sure do wish there was, it would be nice. Most users and myself rarely have this issue, is there something about your device that is different? Or is the image extremely high resolution?

**Comment by gotson** [comment]
The image is 1987x3056, my phone is a OnePlus6T with a resolution of 1080x2280.

**Comment by sethchhim** [comment]
Could you email me a sample book to test? I will use an emulator of 3000x2000 with 2gb of ram.

sethchhim@gmail.com

**Comment by gotson** [comment]
> Could you email me a sample book to test? I will use an emulator of 3000x2000 with 2gb of ram.
> 
> [sethchhim@gmail.com](mailto:sethchhim@gmail.com)

I've sent you a Dropbox link to the file.

**Comment by sethchhim** [comment]
Stock Android 9.0
3000x2000
2gb Ram
Downsizing Setting 9999

The sample book loads fine in both remote and local state. The memory consumption is steady at around 350mb average, no signs of any runaway memory leak. I am unable to recreate your issue.

**Comment by sethchhim** [comment]
This could be attributed to OnePlus' aggressive memory management. Chinese os are known for this to push battery performance. Sometimes they have a disable battery optimization setting to opt out of this feature, maybe you can try that. Unfortunately, I can not test this for you.

**Comment by Tormenator1** [comment]
I'm having the same issue on a Nexus 5x.

**Comment by sethchhim** [comment]
@gotson @Tormenator1 
The default target width and height is set to max (1500px). This is a hard-coded setting which works for most users. If you are receiving out of memory errors, you should try to **lower this setting to consume less memory**. This comes at a cost of reduced image quality. Most apps do this automatically and shoot too low resulting in very blurry images so I leave it up to the user to set.

`Settings -> Advanced -> Force Downsizing`

If you know a way of rendering multiple high resolution bitmaps without the attached memory cost, please submit a pull request and I will be happy to review it. Another solution would be to disable the viewpager swipe effect and only load the current bitmap but I have no interest in this.

**Comment by sethchhim** [comment]
Another solution but poor practice: `android:largeHeap`

> Whether your application's processes should be created with a large Dalvik heap. This applies to all processes created for the application. It only applies to the first application loaded into a process; if you're using a shared user ID to allow multiple applications to use a process, they all must use this option consistently or they will have unpredictable results.
> Most apps should not need this and should instead focus on reducing their overall memory usage for improved performance. Enabling this also does not guarantee a fixed increase in available memory, because some devices are constrained by their total available memory.
> 
> To query the available memory size at runtime, use the methods getMemoryClass() or getLargeMemoryClass().

**Comment by gotson** [comment]
That seems absurd with one of the phone with most ram on the market.

**Comment by sethchhim** [comment]
Yes, I agree it is absurd. You can have 1 million gb of ram, but if your os memory management is aggressive it will produce the same behavior. Chinese manufacturers do this to gain a competitive edge in battery benchmarks, it is a known issue throughout the development community. I suspect `largeHeap` would fix your issue but at the cost of decreased performance for everyone else. This is a global manifest setting and can not be optional. So the question is code against a stock environment or code against a modified environment and I choose the former.
